version: '2.1'

services:
  new_tv_shows:
    image: newtvshows
    container_name: NewTvShowsScript
    restart: always
    build: .
    volumes:
      - ./out:/out:z
      - ./config:/config:z
    environment:
      - DB_HOST=192.168.0.2
      - DB_PORT=3307
      - DB_NAME=MyVideos116
      - DB_USER=****
      - DB_PASSWORD=****
      - INTERVAL_MINUTEN=60
      - MAX_ITEMS=200
      - RSS_URL=****
      - TZ=Europe/Zurich
      - DEBUG_LEVEL=Info
    ports: 
        - 28080:5000